version: "3"

services:
  # Service pour MySQL
  db:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: neo_egoist_league
      MYSQL_USER: ego
      MYSQL_PASSWORD: Jinpachi
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - "3306:3306" # Port pour MySQL, pas de conflit ici

  # Service pour phpMyAdmin (port modifié pour éviter conflit avec php)
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
    ports:
      - "8081:80" # Modifié pour éviter conflit avec le serveur PHP

  # Service pour PHP avec Apache (no need for PHP-FPM here)
  php-apache:
    build: .
    container_name: php-apache
    restart: always
    volumes:
      - ./src/public:/var/www/html
      - ./src/app:/var/www/app
    ports:
      - "8080:80" # Port pour Apache (où tu visualises ta page)
    depends_on:
      - db
    networks:
      - default

networks:
  default:
    external: true
    name: mynetwork # Assure-toi que "mynetwork" existe ou crée-le
