INSERT INTO `player` VALUES (1,'Miroku Darai',8,4,1,NULL),(2,'Eita Otoya',NULL,4,1,NULL),(3,'Meguru Bachira',NULL,4,1,NULL),(4,'Teru Kitsunezato',NULL,4,1,NULL),(5,'Haru Hayate',NULL,4,1,NULL),(6,'Itsuki Wakatsuki',NULL,4,1,NULL),(7,'Kazuma Nio',NULL,5,1,NULL),(8,'Hiiragi Reiji',NULL,5,1,NULL),(9,'Hyoma Chigiri',NULL,5,1,NULL),(10,'Seishiro Nagi',NULL,5,1,NULL),(11,'Reo Mikage',NULL,5,1,NULL),(12,'Nijiro Nanase',NULL,2,1,NULL),(13,'Kento Cho',NULL,2,1,NULL),(14,'Rin Itoshi',NULL,2,1,NULL),(15,'Ryusei Shido',NULL,2,1,NULL),(16,'Tsurugi Zantetsu',NULL,2,1,NULL),(17,'Tabito Karasu',NULL,2,1,NULL),(18,'Tokimitsu Aoshi',NULL,2,1,NULL),(19,'Ikki Niko',NULL,3,1,NULL),(20,'Jyubei Aryu',NULL,3,1,NULL),(21,'Oliver Aiku',NULL,3,1,NULL),(22,'Baro Shoei',NULL,3,1,NULL),(23,'Ishikari Yukio',NULL,3,1,NULL),(24,'Shuto Sendo',NULL,3,1,NULL),(25,'Gen Fukaku',NULL,3,1,NULL),(26,'Igarashi Gurimu',NULL,1,1,NULL),(27,'Kurona Ranze',NULL,1,1,NULL),(28,'Teppei Neru',NULL,1,1,NULL),(29,'Isagi Yoichi',NULL,1,1,NULL),(30,'Bachman',NULL,1,3,NULL),(31,'Gin Gagamaru',NULL,1,1,NULL),(32,'Hiori Yo',NULL,1,1,NULL),(33,'Kenyu Yukimiya',NULL,1,1,NULL),(34,'Raichi Jingo',NULL,1,1,NULL),(35,'Noel Noa',NULL,1,2,NULL),(36,'Michael Kaiser',NULL,1,3,NULL),(37,'Alexis Ness',NULL,1,3,NULL),(38,'Benedict Grim',NULL,1,3,NULL),(39,'Erik Gesner',NULL,1,3,NULL),(40,'Rensuke Kunigami',NULL,1,1,NULL),(41,'Jin Kiyora',NULL,1,1,NULL),(42,'Ali',NULL,1,3,NULL),(43,'Mensah',NULL,1,3,NULL),(44,'Igor Schneider',NULL,1,3,NULL),(45,'Theo Sachs',NULL,1,3,NULL),(46,'Ndiaye',NULL,1,3,NULL),(47,'Julian Loki',NULL,2,2,NULL),(48,'Charles Chevalier',NULL,2,2,NULL),(49,'Chapa',NULL,2,2,NULL),(50,'Akira Endoji',NULL,2,1,NULL),(51,'Haruhiko Yuzu',NULL,2,1,NULL),(52,'Renoir',NULL,2,2,NULL),(53,'Gabon',NULL,2,2,NULL),(54,'Michelin',NULL,2,2,NULL),(55,'Chris Prince',NULL,5,88,NULL),(56,'Agi',NULL,5,88,NULL),(57,'Driver',NULL,5,88,NULL),(58,'Swift',NULL,5,88,NULL),(59,'Busby',NULL,5,88,NULL),(60,'Rook',NULL,5,88,NULL),(61,'Young',NULL,5,88,NULL),(62,'Arthur',NULL,5,88,NULL),(63,'Damon',NULL,5,88,NULL),(64,'Kairu Saramadara',NULL,5,1,NULL),(65,'Taiga Tsunzaki',NULL,5,1,NULL),(66,'Hajime Nishioka',NULL,5,1,NULL),(67,'Junichi Wanima',NULL,5,1,NULL),(68,'Marc Snuffy',NULL,3,86,NULL),(69,'Don Lorenzo',NULL,3,68,NULL),(70,'Drago',NULL,3,68,NULL),(71,'Peron',NULL,3,68,NULL),(72,'Abdi',NULL,3,68,NULL),(73,'Rico',NULL,3,68,NULL),(74,'Canali',NULL,3,68,NULL),(75,'Shingen Tanaka',NULL,3,1,NULL),(76,'Kyohei Shiguma',NULL,3,1,NULL),(77,'Lavinho',NULL,4,5,NULL),(78,'Ignacio Lara',NULL,4,30,NULL),(79,'Ruiz',NULL,4,30,NULL),(80,'Picasso',NULL,4,30,NULL),(81,'Espesso',NULL,4,30,NULL),(82,'So',NULL,4,30,NULL),(83,'Bos',NULL,4,30,NULL),(84,'Gomez',NULL,4,30,NULL),(85,'Uraziz',NULL,4,30,NULL),(86,'Moro',NULL,4,30,NULL),(87,'Tetsu Sokura',NULL,4,1,NULL),(88,'Aiki Himizu',NULL,4,1,NULL),(89,'Shizuka Haiji',NULL,4,1,NULL),(90,'Birkenstock',NULL,1,3,NULL);

INSERT INTO `image` (`url`) VALUES 
/* Miroku Darai */ ('Miroku Darai.jpg'),
/* Eita Otoya */ ('Eita Otoya.jpg'),
/* Meguru Bachira */ ('Meguru Bachira.jpg'),
/* Teru Kitsunezato */ ('Teru Kitsunezato.jpg'),
/* Haru Hayate */ ('Haru Hayate.jpg'),
/* Itsuki Wakatsuki */ ('Itsuki Wakatsuki.jpg'),
/* Kazuma Nio */ ('Kazuma Nio.jpg'),
/* Hiiragi Reiji */ ('Hiiragi Reiji.jpg'),
/* Hyoma Chigiri */ ('Hyoma Chigiri.jpg'),
/* Seishiro Nagi */ ('Seishiro Nagi.jpg'),
/* Reo Mikage */ ('Reo Mikage.jpg'),
/* Nijiro Nanase */ ('Nijiro Nanase.jpg'),
/* Kento Cho */ ('Kento Cho.jpg'),
/* Rin Itoshi */ ('Rin Itoshi.jpg'),
/* Ryusei Shido */ ('Ryusei Shido.jpg'),
/* Tsurugi Zantetsu */ ('Tsurugi Zantetsu.jpg'),
/* Tabito Karasu */ ('Tabito Karasu.jpg'),
/* Tokimitsu Aoshi */ ('Tokimitsu Aoshi.jpg'),
/* Ikki Niko */ ('Ikki Niko.jpg'),
/* Jyubei Aryu */ ('Jyubei Aryu.jpg'),
/* Oliver Aiku */ ('Oliver Aiku.jpg'),
/* Baro Shoei */ ('Baro Shoei.jpg'),
/* Ishikari Yukio */ ('Ishikari Yukio.jpg'),
/* Shuto Sendo */ ('Shuto Sendo.jpg'),
/* Gen Fukaku */ ('Gen Fukaku.jpg'),
/* Igarashi Gurimu */ ('Igarashi Gurimu.jpg'),
/* Kurona Ranze */ ('Kurona Ranze.jpg'),
/* Teppei Neru */ ('Teppei Neru.jpg'),
/* Isagi Yoichi */ ('Isagi Yoichi.jpg'),
/* Bachman */ ('Bachman.jpg'),
/* Gin Gagamaru */ ('Gin Gagamaru.jpg'),
/* Hiori Yo */ ('Hiori Yo.jpg'),
/* Kenyu Yukimiya */ ('Kenyu Yukimiya.jpg'),
/* Raichi Jingo */ ('Raichi Jingo.jpg'),
/* Noel Noa */ ('Noel Noa.jpg'),
/* Michael Kaiser */ ('Michael Kaiser.jpg'),
/* Alexis Ness */ ('Alexis Ness.jpg'),
/* Benedict Grim */ ('Benedict Grim.jpg'),
/* Erik Gesner */ ('Erik Gesner.jpg'),
/* Rensuke Kunigami */ ('Rensuke Kunigami.jpg'),
/* Jin Kiyora */ ('Jin Kiyora.jpg'),
/* Ali */ ('Ali.jpg'),
/* Mensah */ ('Mensah.jpg'),
/* Igor Schneider */ ('Igor Schneider.jpg'),
/* Theo Sachs */ ('Theo Sachs.jpg'),
/* Ndiaye */ ('Ndiaye.jpg'),
/* Julian Loki */ ('Julian Loki.jpg'),
/* Charles Chevalier */ ('Charles Chevalier.jpg'),
/* Chapa */ ('Chapa.jpg'),
/* Akira Endoji */ ('Akira Endoji.jpg'),
/* Haruhiko Yuzu */ ('Haruhiko Yuzu.jpg'),
/* Renoir */ ('Renoir.jpg'),
/* Gabon */ ('Gabon.jpg'),
/* Michelin */ ('Michelin.jpg'),
/* Chris Prince */ ('Chris Prince.jpg'),
/* Agi */ ('Agi.jpg'),
/* Driver */ ('Driver.jpg'),
/* Swift */ ('Swift.jpg'),
/* Busby */ ('Busby.jpg'),
/* Rook */ ('Rook.jpg'),
/* Young */ ('Young.jpg'),
/* Arthur */ ('Arthur.jpg'),
/* Damon */ ('Damon.jpg'),
/* Kairu Saramadara */ ('Kairu Saramadara.jpg'),
/* Taiga Tsunzaki */ ('Taiga Tsunzaki.jpg'),
/* Hajime Nishioka */ ('Hajime Nishioka.jpg'),
/* Junichi Wanima */ ('Junichi Wanima.jpg'),
/* Marc Snuffy */ ('Marc Snuffy.jpg'),
/* Don Lorenzo */ ('Don Lorenzo.jpg'),
/* Drago */ ('Drago.jpg'),
/* Peron */ ('Peron.jpg'),
/* Abdi */ ('Abdi.jpg'),
/* Rico */ ('Rico.jpg'),
/* Canali */ ('Canali.jpg'),
/* Shingen Tanaka */ ('Shingen Tanaka.jpg'),
/* Kyohei Shiguma */ ('Kyohei Shiguma.jpg'),
/* Lavinho */ ('Lavinho.jpg'),
/* Ignacio Lara */ ('Ignacio Lara.jpg'),
/* Ruiz */ ('Ruiz.jpg'),
/* Picasso */ ('Picasso.jpg'),
/* Espesso */ ('Espesso.jpg'),
/* So */ ('So.jpg'),
/* Bos */ ('Bos.jpg'),
/* Gomez */ ('Gomez.jpg'),
/* Uraziz */ ('Uraziz.jpg'),
/* Moro */ ('Moro.jpg'),
/* Tetsu Sokura */ ('Tetsu Sokura.jpg'),
/* Aiki Himizu */ ('Aiki Himizu.jpg'),
/* Shizuka Haiji */ ('Shizuka Haiji.jpg'),
/* Birkenstock */ ('Birkenstock.jpg');
