
INSERT INTO player_weapon (player_id, weapon_id)
SELECT p.id, w.id
FROM player p
JOIN weapon w ON (
    (p.name Like 'Isagi' AND w.name IN ('Meta Vision', 'Direct Shot','Adaptability','Off-the-Ball Movements','Reflex','Flow State','Spatial Awareness'))
 OR (p.name Like 'Chigiri' AND w.name IN ('Speed', 'Ball Control','Crossing','Controlled Shot'))
 OR (p.name Like 'Barou' AND w.name IN ('Predator Eye', 'Physique','Flow State','Chop Feints','Charging Skill','Middle Shot'))
 OR (p.name Like 'Michael Kaiser' AND w.name IN ('Metavision','Flow State','Kaiser Impact','Off the ball Movements','Predator Eye','Spatial Awareness'))   
 OR (p.name Like 'Noel Noa' AND w.name IN ('All-Powerful Shot','Acceleration','Dribbling','Off the ball Movements','Ambidexterity','Physique'))   
 OR (p.name Like 'Alexis Ness' AND w.name IN ('Flexible Ankles','Dribbling','Passing','Flow State'))   
 OR (p.name Like 'Marc Snuffy' AND w.name IN ('Metavision','Ball Control','Physique','Off the ball Movements'))   
 OR (p.name Like 'Benedict Grim' AND w.name IN ('Crossing','Dribbling','Physique'))   
 OR (p.name Like 'Erik Gesner' AND w.name IN ('Trapping','Ball Control'))          
 OR (p.name Like 'Teppei Neru' AND w.name IN ('Acceleration'))   
 OR (p.name Like 'Gurimu Igarashi' AND w.name IN ('Diving')) 
 OR (p.name Like 'Jin Kiyora' AND w.name IN ('Physique','Core Balance','Dribbling','Ground Shots','Flow State'))   
 OR (p.name Like 'Yo Hiori' AND w.name IN ('Metavision','Ball Control','Reflex','Flow State','Passing'))   
 OR (p.name Like 'Jingo Raichi' AND w.name IN ('Stamina','Physique','Man-Marking'))   
 OR (p.name Like 'Ranze Kurona' AND w.name IN ('Speed','Passing','Off the ball Movements'))   
 OR (p.name Like 'Gin Gagamaru' AND w.name IN ('Flexibility','Explosive Reaction','Springlike Body','Flow State'))   
 OR (p.name Like 'Kenyu Yukimiya' AND w.name IN ('Predator Eye','Flow State','Sword Screw','Gyro Shot','Speed','Dribbling'))   
 OR (p.name Like 'Rensuke Kunigami' AND w.name IN ('Flow State','Ambidexterity','Physique','Finesse Shot','Man-Marking'))   
 OR (p.name Like 'Charles Chevalier' AND w.name IN ('Metavision','Passing','Off the ball Movements'))   
 OR (p.name Like 'Julian Loki' AND w.name IN ('Godspeed','Agility'))   
 OR (p.name Like 'Tokimitsu Aoshi' AND w.name IN ('Agility','Ball Stamina','Physique'))   
 OR (p.name Like 'Tabito Karasu' AND w.name IN ('Metavision','Feints','Ball Control','Analytical Ability'))   
 OR (p.name Like 'Tsurugi Zantetsu' AND w.name IN ('Acceleration','Left Foot Shot'))   
 OR (p.name Like 'Ryusei Shido' AND w.name IN ('Drive Shot','Reflex','Acceleration','Spatial Awareness','Physique','Off the ball Movements'))   
 OR (p.name Like 'Rin Itoshi' AND w.name IN ('Predator Eye','Flow State','Puppet Control','Dribbling','Spatial Awareness','Off the ball Movements'))   
 OR (p.name Like 'Kento Cho' AND w.name IN ('Height'))   
 OR (p.name Like 'Nijiro Nanase' AND w.name IN ('Ambidexterity','Off the ball Movements'))    
 OR (p.name Like 'Rico' AND w.name IN ('Acceleration'))   
 OR (p.name Like 'Peron' AND w.name IN ('Metavision','Ball Control','Physique','Off the ball Movements'))   
 OR (p.name Like 'Drago' AND w.name IN ('Metavision','Ball Control','Physique','Off the ball Movements'))   
 OR (p.name Like 'Don Lorenzo' AND w.name IN ('Dribbling','Man-Marking'))   
 OR (p.name Like 'Gen Fukaku' AND w.name IN ('Physique'))   
 OR (p.name Like 'Shuto Sendo' AND w.name IN ('Stamina'))   
 OR (p.name Like 'Ishikari Yukio' AND w.name IN ('Headers','Vertical Jump'))   
 OR (p.name Like 'Oliver Aiku' AND w.name IN ('Metavision','Flow State','Physique','Reflex','Spatial Awareness'))   
 OR (p.name Like 'Jyubei Aryu' AND w.name IN ('Headers','Long Reach','Jumping Power'))   
 OR (p.name Like 'Ikki Niko' AND w.name IN ('Metavision','Spatial Awareness','Ball Stealing'))   
 OR (p.name Like 'Aiki Himizu' AND w.name IN ('Pressing','Lie Detection','Feints'))   
 OR (p.name Like 'Lavinho' AND w.name IN ('Metavision','Ball Control','Physique','Off the ball Movements'))   
 OR (p.name Like 'Meguru Bachira' AND w.name IN ('Flow State','Bee Shot','Passing','Dribbling'))   
 OR (p.name Like 'Eita Otoya' AND w.name IN ('Speed','Off the ball Movements'))   
 OR (p.name Like 'Miroku Darai' AND w.name IN ('Prediction','Off the ball Movements'))   
 OR (p.name Like 'Kazuma Nio' AND w.name IN ('Physique','Pressing'))   
 OR (p.name Like 'Hiiragi Reiji' AND w.name IN ('Trapping','Prediction'))   
 OR (p.name Like 'Seishiro Nagi' AND w.name IN ('Trapping','Ball Control','Flow State'))   
 OR (p.name Like 'Reo Mikage' AND w.name IN ('Metavision','Flow State','Copycat','Dexterity'))
 OR (p.name Like 'Chris Prince' AND w.name IN ('Knuckleball','Perfect Physicality'))   
 OR (p.name Like 'Agi' AND w.name IN ('Physique','Long Reach','Vertical Jump'))
 OR (p.name Like 'Junichi Wanima' AND w.name IN ('Eye Contact'))   
);